# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          #- {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: List
        run: ls -lR /opt/gfortran

      - name: Dependencies
        run: ./run.sh install_deps

      - name: Test
        run: ./run.sh run_tests

      - name: Logs
        run: ./run.sh dump_logs
        if: failure()

      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #  run: ./run.sh coverage
